'use client';
import {useEffect,useMemo,useState} from 'react';
type EventRow={id:string;slug:string;name:string;event_type:string|null;location:string|null;state:string;starts_at:string|null;ends_at:string|null;uploads_enabled:boolean;album_enabled:boolean;primary_color:string;secondary_color:string};
type Photo={id:string;url:string;status:string;uploaded_at:string};
const api=async(url:string,init?:RequestInit)=>{const r=await fetch(url,init);const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'הפעולה נכשלה');return b};
export default function Admin(){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[logged,setLogged]=useState(false),[events,setEvents]=useState<EventRow[]>([]),[selected,setSelected]=useState<EventRow|null>(null),[photos,setPhotos]=useState<Photo[]>([]),[tab,setTab]=useState<'overview'|'edit'|'media'|'access'|'new'>('overview'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[pin,setPin]=useState('');
 const [draft,setDraft]=useState({name:'',eventType:'חתונה',location:'',slug:'',startsAt:'',endsAt:'',pin:''});
 const loadEvents=async()=>{try{const b=await api('/api/admin/events');setEvents(b.events);setLogged(true);if(!selected&&b.events[0])setSelected(b.events[0])}catch{setLogged(false)}};
 useEffect(()=>{void loadEvents()},[]);
 useEffect(()=>{if(selected&&tab==='media')void loadMedia(selected.id)},[selected,tab]);
 const login=async()=>{setBusy(true);try{await api('/api/admin/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})});await loadEvents();setMessage('ברוכים הבאים ל-Digi')}catch(e){setMessage(e instanceof Error?e.message:'שגיאה')}finally{setBusy(false)}};
 const loadMedia=async(id:string)=>{try{const b=await api(`/api/media?eventId=${id}&status=pending`);setPhotos(b.photos||[])}catch(e){setMessage(e instanceof Error?e.message:'שגיאה')}};
 const saveEvent=async()=>{if(!selected)return;setBusy(true);try{const b=await api('/api/admin/events',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({eventId:selected.id,name:selected.name,eventType:selected.event_type,location:selected.location,startsAt:selected.starts_at,endsAt:selected.ends_at,uploadsEnabled:selected.uploads_enabled,albumEnabled:selected.album_enabled,primaryColor:selected.primary_color,secondaryColor:selected.secondary_color})});setSelected(b.event);await loadEvents();setMessage('האירוע נשמר')}catch(e){setMessage(e instanceof Error?e.message:'שגיאה')}finally{setBusy(false)}};
 const createEvent=async()=>{setBusy(true);try{const b=await api('/api/admin/events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(draft)});await loadEvents();setSelected(b.event);setTab('overview');setMessage('האירוע נוצר בהצלחה')}catch(e){setMessage(e instanceof Error?e.message:'שגיאה')}finally{setBusy(false)}};
 const moderate=async(photoId:string,status:string)=>{if(!selected)return;try{await api('/api/staff/moderate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({eventId:selected.id,photoId,status,expectedStatus:'pending'})});setPhotos(v=>v.filter(p=>p.id!==photoId))}catch(e){setMessage(e instanceof Error?e.message:'שגיאה')}};
 const changePin=async()=>{if(!selected)return;try{await api('/api/admin/pin',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({eventId:selected.id,pin})});setPin('');setMessage('ה-PIN הוחלף והחיבורים הישנים בוטלו')}catch(e){setMessage(e instanceof Error?e.message:'שגיאה')}};
 const eventUrl=useMemo(()=>selected&&typeof location!=='undefined'?`${location.origin}/e/${selected.slug}`:'',[selected]);
 if(!logged)return <main className="adminLogin"><div className="adminLoginCard"><span className="brand">digi</span><small>ADMIN STUDIO</small><h1>ניהול האירועים שלכם</h1><p>כניסה מאובטחת למערכת הניהול</p><label>אימייל<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com"/></label><label>סיסמה<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={busy} onClick={()=>void login()}>{busy?'מתחבר…':'כניסה למערכת'}</button>{message&&<p className="notice">{message}</p>}</div></main>;
 return <main className="adminShell"><aside className="adminSide"><div><span className="brand">digi</span><small>EVENT STUDIO</small></div><nav><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>סקירה</button><button className={tab==='edit'?'active':''} onClick={()=>setTab('edit')}>עיצוב והגדרות</button><button className={tab==='media'?'active':''} onClick={()=>setTab('media')}>תמונות ואישורים</button><button className={tab==='access'?'active':''} onClick={()=>setTab('access')}>קישורים ו-PIN</button><button className={tab==='new'?'active':''} onClick={()=>setTab('new')}>＋ אירוע חדש</button></nav></aside><section className="adminContent"><header className="adminTop"><div><small>מרכז ניהול</small><h1>{selected?.name||'האירועים שלי'}</h1></div><select value={selected?.id||''} onChange={e=>setSelected(events.find(x=>x.id===e.target.value)||null)}>{events.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></header>{message&&<div className="toast">{message}</div>}
 {tab==='overview'&&<div className="dashboard"><div className="welcomeCard"><small>{selected?.event_type||'אירוע'}</small><h2>{selected?.name}</h2><p>{selected?.location||'המיקום טרם הוגדר'}</p><div><a href={eventUrl} target="_blank">פתיחת עמוד האירוע</a><button onClick={()=>setTab('edit')}>עריכת האירוע</button></div></div><div className="statGrid"><article><b>{photos.length}</b><span>ממתינות לאישור</span></article><article><b>{selected?.uploads_enabled?'פעיל':'כבוי'}</b><span>העלאת אורחים</span></article><article><b>{selected?.album_enabled?'פתוח':'סגור'}</b><span>אלבום ציבורי</span></article></div><div className="eventsList"><h2>האירועים שלי</h2>{events.map(e=><button key={e.id} onClick={()=>{setSelected(e);setTab('edit')}}><span><b>{e.name}</b><small>{e.slug} · {e.state}</small></span><em>ניהול ←</em></button>)}</div></div>}
 {tab==='edit'&&selected&&<div className="adminForm"><h2>עיצוב והגדרות</h2><div className="formGrid"><label>שם האירוע<input value={selected.name} onChange={e=>setSelected({...selected,name:e.target.value})}/></label><label>סוג האירוע<input value={selected.event_type||''} onChange={e=>setSelected({...selected,event_type:e.target.value})}/></label><label>מיקום<input value={selected.location||''} onChange={e=>setSelected({...selected,location:e.target.value})}/></label><label>תחילת האירוע<input type="datetime-local" value={selected.starts_at?.slice(0,16)||''} onChange={e=>setSelected({...selected,starts_at:e.target.value})}/></label><label>סיום האירוע<input type="datetime-local" value={selected.ends_at?.slice(0,16)||''} onChange={e=>setSelected({...selected,ends_at:e.target.value})}/></label><label>צבע ראשי<input type="color" value={selected.primary_color} onChange={e=>setSelected({...selected,primary_color:e.target.value})}/></label></div><div className="switches"><label><input type="checkbox" checked={selected.uploads_enabled} onChange={e=>setSelected({...selected,uploads_enabled:e.target.checked})}/> העלאת אורחים פעילה</label><label><input type="checkbox" checked={selected.album_enabled} onChange={e=>setSelected({...selected,album_enabled:e.target.checked})}/> האלבום פתוח</label></div><button className="primary" disabled={busy} onClick={()=>void saveEvent()}>שמירת שינויים</button></div>}
 {tab==='media'&&selected&&<div className="mediaAdmin"><div className="sectionTitle"><div><small>MODERATION</small><h2>תמונות ממתינות</h2></div><button onClick={()=>void loadMedia(selected.id)}>רענון</button></div><div className="moderationGrid">{photos.map(p=><article key={p.id}><img src={p.url} alt="תמונה ממתינה"/><div><button className="approve" onClick={()=>void moderate(p.id,'approved')}>אישור</button><button onClick={()=>void moderate(p.id,'private')}>פרטי</button><button className="reject" onClick={()=>void moderate(p.id,'rejected')}>דחייה</button></div></article>)}</div>{!photos.length&&<div className="emptyState">אין כרגע תמונות שממתינות לאישור</div>}</div>}
 {tab==='access'&&selected&&<div className="adminForm"><h2>קישורים והרשאות</h2><label>קישור לאירוע<div className="copyBox"><code>{eventUrl}</code><button onClick={()=>navigator.clipboard.writeText(eventUrl)}>העתקה</button></div></label><label>קישור לשושבינות<div className="copyBox"><code>{eventUrl}/moderator</code><button onClick={()=>navigator.clipboard.writeText(`${eventUrl}/moderator`)}>העתקה</button></div></label><label>PIN חדש לשושבינות<input className="pinInput" inputMode="numeric" maxLength={4} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,4))}/></label><button className="primary" disabled={pin.length!==4} onClick={()=>void changePin()}>החלפת PIN</button></div>}
 {tab==='new'&&<div className="adminForm"><h2>יצירת אירוע חדש</h2><div className="formGrid"><label>שם האירוע<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>קישור באנגלית<input value={draft.slug} onChange={e=>setDraft({...draft,slug:e.target.value})} placeholder="dudi-and-noa"/></label><label>סוג האירוע<input value={draft.eventType} onChange={e=>setDraft({...draft,eventType:e.target.value})}/></label><label>מיקום<input value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})}/></label><label>התחלה<input type="datetime-local" value={draft.startsAt} onChange={e=>setDraft({...draft,startsAt:e.target.value})}/></label><label>סיום<input type="datetime-local" value={draft.endsAt} onChange={e=>setDraft({...draft,endsAt:e.target.value})}/></label><label>PIN לשושבינות<input inputMode="numeric" maxLength={4} value={draft.pin} onChange={e=>setDraft({...draft,pin:e.target.value.replace(/\D/g,'').slice(0,4)})}/></label></div><button className="primary" disabled={busy} onClick={()=>void createEvent()}>יצירת האירוע</button></div>}
 </section></main>
}
